### ISSUE TITLE
Shortfin LLM Regression from IREE version `3.1.0rc20241203`

### ISSUE THREAD

**Issue by stbaione** [nod-ai/shark-ai#638]
# Description

It appears that there was a regression for Shortfin LLM introduced by: [0f21989438e5c422287882cb67a315329b7b744e](https://github.com/iree-org/iree/commit/0f21989438e5c422287882cb67a315329b7b744e)

Have already filed an [IREE Issue](https://github.com/iree-org/iree/issues/19360)

```Memory access fault by GPU node-8 (Agent handle: 0x5610e4b7e750) on address 0x7eff79e03000. Reason: Unknown.```

Can be seen in this [CI - sharktank perplexity short](https://github.com/nod-ai/shark-ai/actions/runs/12144449804/job/33863814189#step:6:42) run, where the iree-base-compiler/iree-base-runtime version was upgraded from 3.1.0rc20241202 to 3.1.0rc20241203.

I saw the same error when validating my own CI in a PR, and was able to reproduce it locally with the shortfin server.

# Repro Steps
I was able to bisect and verify the issue by exporting/compiling fresh model artifacts and sending a request to the shortfin LLM server. Repro steps outlined below:

1. Create new directory
2. Download Llama3_8b_fp16 w/ sharktank.utils.hf_datasets:
```bash
python -m sharktank.utils.hf_datasets llama3_8B_fp16 --local-dir ./artifacts

```
3. Export to MLIR:

```bash
python -m sharktank.examples.export_paged_llm_v1 --gguf-file=./artifacts/meta-llama-3.1-8b-instruct.f16.gguf --output-mlir=./artifacts/model.mlir --output-config=./artifacts/config.json --bs=1,4

```
5. Compile model:

```
iree-compile ./artifacts/model.mlir -o ./artifacts/model.vmfb

```
7. Save the following json data to ./artifacts/config.json:
```json
{
        "module_name": "module",
        "module_abi_version": 1,
        "max_seq_len": 131072,
        "attn_head_count": 8,
        "attn_head_dim": 128,
        "prefill_batch_sizes": [1, 4],
        "decode_batch_sizes": [1, 4],
        "transformer_block_count": 32,
        "paged_kv_cache": {"block_seq_stride": 16, "device_block_count": 256},
    }

```

9. Start Shortfin LLM Server:

```bash
python -m shortfin_apps.llm.server --tokenizer_json=./artifacts/tokenizer.json --model_config=./artifacts/config.json --vmfb=./artifacts/model.vmfb --parameters=./artifacts/meta-llama-3.1-8b-instruct.f16.gguf --device=hip --port=8003

```
11. Send request to shortfin LLM server:

```python
import requests
base_url = "http://localhost:8003/generate"
payload = {'text': 'Hello, how are you?', 'sampling_params': {'max_completion_tokens': 50}}
resp = requests.post(base_url, json=payload)

```

# Validating:
With iree set to [4ee7d600c9ef024f85c7f6860abdebc1a964f7bc](https://github.com/iree-org/iree/commit/4ee7d600c9ef024f85c7f6860abdebc1a964f7bc):

```bash
>>> resp.text
"data:  I am so happy to see you here! I hope you are doing great and that everything is going well for you. I just wanted to reach out and say hello and see how you're doing. I've been thinking about you and wanted to check in\n\n"

```

With iree set to [0f21989438e5c422287882cb67a315329b7b744e](https://github.com/iree-org/iree/commit/0f21989438e5c422287882cb67a315329b7b744e):

```text
Request fails and server outputs:

Memory access fault by GPU node-3 (Agent handle: 0x55dd6a5136b0) on address 0x7f6a3be00000. Reason: Unknown.
Aborted (core dumped)
```

**Comment by stbaione** [comment]
Issue resolved by: [cb5be1dbd3560f692578c137eadbb413b41e44c7](https://github.com/iree-org/iree/commit/cb5be1dbd3560f692578c137eadbb413b41e44c7)
